name: vamenv
channels:
  - conda-forge
dependencies:
  - python=3.8  # Streamlit 1.35.0 requires Python 3.8
  - numpy>=1.19.3
  - pandas>=1.3.4
  - streamlit>=1.35.0
  - aiohttp
  - requests
  - tqdm
  - pylint=3.2.7
  # Add any other dependencies your project needs
  - pip
  - pip:
    - pyeuropeana
    - coveralls
